### ISSUE TITLE
dynamic fields

### ISSUE THREAD

**Issue by PhilipeTakeo** [open-rpa/openrpa#138]
Hi!

I need some help again, in fact I have two questions. 

First, at web site http://rpachallenge.com/  I created a workflow that "highlight" an element, this element change its place ever time i click on submit. But when the submit button isn't on screen the robot doesn't work. I think this is easy to solve, but i don't know how.

Second, I need to make an workflow like the first one, but instead of "highlight" the word, I need to write inside the field. 
e.g: I'd like to write the First Name field and click Submit, but after i click submit, the First Name field will not only change its place, i think it will change its ID number.

Can you check this please?

p.s: i attached the "highlightelement" workflow.

Thanks.

[rpachallenge.zip](https://github.com/open-rpa/openrpa/files/3831958/rpachallenge.zip)

**Comment by skadefro** [comment]
Why are you using image recognition on a webpage ? Why not use the chrome addon ?

**Comment by PhilipeTakeo** [comment]
I don't know the best way to make workflows and use some functions yet. I'm studying about RPA and learning to create robots with your software.

**Comment by skadefro** [comment]
What a fun site :-) ... i did not know about that.
Ok, first of all, this is a challenge, so they forced you to be creative. Since most websites use ID as an unique identifier they deliberately made this hard by creating random id's and use ng-reflect-name as the unique identifier.
You can easly catch those with xpath, for instance phone number is
`//*[@ng-reflect-name=\"labelPhone\"]`
Secondly, they did something "funky" with the submit button, so we need to do a real mouse click to make it work, so i set virtual to false on the elementclick activity 
![image](https://user-images.githubusercontent.com/4155937/68602877-74920e80-04a7-11ea-8896-23c98b5017d7.png)
I'm not sure what you wanted with the highlights so i did not do anything with those.
You can see/test my version of the workflow here 
[rpachallenge.zip](https://github.com/open-rpa/openrpa/files/3832216/rpachallenge.zip)

**Comment by PhilipeTakeo** [comment]
ReadRange doesn't work...

The xlsx file is at my documents folder


![Screenshot_1](https://user-images.githubusercontent.com/56645803/68609686-c715ff80-0494-11ea-9a60-c6455263753f.jpg)

**Comment by skadefro** [comment]
I don't understand all of the error message, but from what i do understand it looks like you don't have excel installed, is that correct ?
If so, I don't have an activity for reading excel files without excel installed yet. But i can create one. That should not take more than 1-2 days ...

**Comment by PhilipeTakeo** [comment]
I have excel installed, it is microsoft office professional 2013...

I'm attaching a workflow that take some names from word.docx and put them in excel.xlsx. Take a look how I open the excel file. It doesn't open using just "OpenApplication" i have to do somes clicks to open.
Open a word.docx works well.


[Lista de nome excel e word.zip](https://github.com/open-rpa/openrpa/files/3832791/Lista.de.nome.excel.e.word.zip)
