### ISSUE TITLE
Run a workflow in cron job.

### ISSUE THREAD

**Issue by NiclausLiu** [open-rpa/openrpa#154]
Hi Allan
I've made a workflow, and I hope it can excute automatically at 8 a.m. everyday.
How can I make it work?
I'm sorry my English is not good, I hope you can understand what I say.
I will be very grateful for your help.
Thanks

**Comment by skadefro** [comment]
You have 2 options.
You can create a workflow that never ends, and then use Delay to "wake up" once in a while and check if it's time to run the workflow.
You can also use OpenFlow, and add a schedulering node and make it call the robot at the specified time ( by using openflow, you can also monitor if the workflow runs successfully, so if the machine turned of, or robot not running you can catch that from openflow )

Nodered example using the module node-red-contrib-scheduler
![image](https://user-images.githubusercontent.com/4155937/69716887-4f3e0b00-110b-11ea-939f-a1ba7a2c087a.png)
Might not be perfect, but it shows what I mean.
![image](https://user-images.githubusercontent.com/4155937/69716624-ae4f5000-110a-11ea-8172-896d10a02cf1.png)

**Comment by skadefro** [comment]
This question comes up a lot, so want to add a few more options.
You can schedule jobs from an external application, or using [microsoft task scheduler](https://docs.microsoft.com/en-us/windows/win32/taskschd/about-the-task-scheduler) and then execute a workflow using commandline parameters to the robot. You can read more about [that here](https://github.com/open-rpa/openrpa/issues/224#issuecomment-585638640).

Using nodered, node-red-contrib-scheduler is still and option, but right now i mostly use [node-red-contrib-cron module](https://flows.nodered.org/node/node-red-contrib-cron) You can lookup the cron syntax on [crontab.guru](https://crontab.guru/)

And while speaking about NodeRED. Just as you can easily install the robot and use [app.openiap.io](https://app.openiap.io) as your openflow instance, you can also run NodeRED locally, connected to remote openflow instance like [app.openiap.io](https://app.openiap.io). You can read more about [that here](https://github.com/open-rpa/openflow#quick-start-running-openflow-nodered-using-npm)

**Comment by skadefro** [comment]
Since i keep linking to this post, I will add the latest option here too.
With openrpa version 1.1.x you can now also manage the robots using powershell ( if also using openflow! )
If you open powershell on a machine that has openrpa installed and you have run the robot and logged in, powershell will use the same credentials to talk to openflow. One of the things you can do from PowerShell is run workflows on robots both local and remote using Invoke-OpenRPA
![image](https://user-images.githubusercontent.com/4155937/97022168-15ac9480-1554-11eb-9466-3903d5ab311b.png)
