### ISSUE TITLE
Disconnected Unable to connect to the remote server

### ISSUE THREAD

**Issue by weizier** [open-rpa/openrpa#194]
there is no login page when I start OpenRPA, and it shows "NM: offline" at the bottom left corner.

**Comment by skadefro** [comment]
Are you connecting from china?
Then you can not see my demo installation on openflow, since it’s hosted st google.
Either use a vpn that allows access to google are you can use the robot offline by removing the url to the demo server in the settings file

Nm: offline means you have not installed the browser addon in chrome/firefox and/or the browser is not running, there are links to both on settings tab inside the robot

**Comment by weizier** [comment]
There are two wierd things. 

1. Yes, I'm in China, but I can open demo1.openrpa.dk in my network. Does it need to set proxy inside openrpa?

2. So I tried to remove the wsurl, but it just didn't work, it is also showing "Connecting to wss://demo1.openrpa.dk",  and I tried restart openrpa, the settings file then rewrites the wsurl to "wss://demo1.openrpa.dk/".

So till now, I can't click "New workflow" or drag any elements in the left column.

Thanks very much!

**Comment by skadefro** [comment]
1) if you can open and see data at https://demo1.openrpa.dk then a proxy or vpn should not be needed. ( You setup proxy under network setting in Internet Explorer, then all .net applications will pick that up )
2) Yes, OpenRPA will update that file often while running, so you need to close down OpenRPA before removing the url from wsurl. 
![image](https://user-images.githubusercontent.com/4155937/71762639-10516100-2ed2-11ea-84b2-cf9230979b9e.png)

If you would like to test openrpa against openflow, or if removing the url from wsurl does not work, then please send the log from Logging tab, inside the robot or we could setup an teamviewer session so i can see your screen and troubleshoot.
![image](https://user-images.githubusercontent.com/4155937/71762655-4b539480-2ed2-11ea-9644-bb4561f2db11.png)

**Comment by weizier** [comment]
It does work! Thank you so much.
