### ISSUE TITLE
ffmanifest / chromemanifest

### ISSUE THREAD

**Issue by arpeeay** [open-rpa/openrpa#212]
The path within the manifest files caused, that the nativemessaginghost.exe could not be found.
"path": "C:\\**Program Files**\\OpenRPA\\OpenRPA.NativeMessagingHost.exe"

I had to change that because of my german configured PC to: 
"path": "C:\\**Programme**\\OpenRPA\\OpenRPA.NativeMessagingHost.exe"
and it works.

Maybe **CSIDL_PROGRAM_FILESX86** and **CSIDL_PROGRAM_FILES** will do this job?

Cheers, Marcus.

**Comment by skadefro** [comment]
Nice catch, thank you.
Yes, that would proberly be the solution, or just use Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles);
I will make a new build within a few days

**Comment by skadefro** [comment]
Sorry for the delay, I've finally had time to look into this. 
I'm not sure this is an issue ?
Let me explain, [here](https://github.com/open-rpa/openrpa/blob/master/OpenRPA.NM/NMHook.cs#L434) the plugin updates the manifest files with the path to where the NativeMessagingHost is. It get's the path from [this property](https://github.com/open-rpa/openrpa/blob/master/OpenRPA.Interfaces/Extensions.cs#L93)  as you can see it gets the path to the openrpa.exe witch should also contain the OpenRPA.NativeMessagingHost.exe 
So no matter where you install the robot, this could should find the correct path.
Moreover, in newer versions of windows, they stopped naming directories using localized names, and only show localized names when looking at them inside explorer, if you for instance open a CMD and do a dir in c:\ you should still see the common english names for users, program files etc. 
So ... 2 questions, 
did the chrome addon not work, and then after updating manifest.json it did work ?
are you sure, it's still working, since the add on will update this file every time you run the robot ?
and 2, if you still have a problem, can i ask you to show me, so i can figure out the exact problem and implement a fix for it ? ( using team viewer or something similar )

**Comment by arpeeay** [comment]
I didn't check this again. I shortly explain what happened a few days ago. I tried to automate a website and always had this error message (not the exact words): "Couldn't find OpenRPA Browser Plugin...". So I searched for the manifest file to see what the absolut path is like. After i changed the path to the mentioned path, everything was fine. I will look this up in the evening, we can do a remote session also this evening. We did that already, so it should work.

**Comment by skadefro** [comment]
Any news on this ? Shall we do a teamviewer session ? you have my email :-)

**Comment by arpeeay** [comment]
Oh, my fault ... 

Yes, I did check this and I run into the same problem each time I update OpenRPA. Once it's updated, it  seems to keep the manifest files in the same condition, so I be able to work with the browsers again.

I'll contact you.

**Comment by skadefro** [comment]
Thank you for the talk, and glad the problem was fixed.
