### ISSUE TITLE
Update versions Of OpenRPA on NuGet

### ISSUE THREAD

**Issue by rodrigoborraschi** [open-rpa/openrpa#237]
Hi Allan!

Could you update the versions of OpenRPA on NuGet ?

Thanks in advance.

**Comment by skadefro** [comment]
I stopped updating the nuget packages because i wanted to improve the user experience and i also have to find a way to differentiate between core components ( things in program files ) and "extension" packages that gives access to new activities and therefore would fits better i the users profile directory.
Thank you for bringing my attention to this, but for now i want to push this for at least a few weeks, till i can add support for managing nuget dependencies in projects and seperate that from updating the core robot, that requires being run as administrator.

**Comment by skadefro** [comment]
I accidentally updated on of the packages while setting up a new nuget repository, and decided to just update it all, so this is now done, even though i didn't really mean too

**Comment by rodrigoborraschi** [comment]
Thank you very much Allan for both the information and the update of the nuget packages :)
