### ISSUE TITLE
Wait for an element - Enhancement

### ISSUE THREAD

**Issue by manashk** [open-rpa/openrpa#359]
Enhancement in the GetElement activity for Browser can make RPA developers life easy, make the automations error free and make OpenRPA workflows much more stable.

1. **Time out:** (Default 3 secs) How long the activity will wait while throwing an error. if the element is found it will proceed to next activity. (already available)
2. **Retry:** (Default 1 ) How many times the activity will retry after timeout to find the element before throwing an error.  if the element is found it will proceed to next activity.
3. **Visible:** Wait till the time element is visible. (Boolean default true)
4. **Interactive:** Wait till the time the element is active to click or type as an example. (Boolean default false)
5. **Continue on Error:** If true, continues to next activity without throwing any error. Try catch won't be able to catch error with this enabled, (Boolean default false)

This will ensure the workflow doesn't give error because of any latency or delay due to any reason.

I know it can be achived with Try and catch or loop but then need to add to many try catch or activities.

**Comment by skadefro** [comment]
Hey, not sure I'm following you on several of these.

1,2) TimeOut already exists, and it keeps trying until the timeout occurs, so what is the point of Retry ?

3) Visible, i could see this making sense, sometimes you can find an element that is not visible, but my definition of visible might not be what others think. for instance, if a element is visible but not on the screen ( you have to scroll for it ) is it then visible ?
I really want to make things as flexible as possible, and since different technologies treat hidden objects differently and it can have different meanings, i feel this might be a bad box of trouble to open (but I'm always open for arguments)

4) This one, as far as i know, would only make sense on windows elements. 
I have added and Interactive boolean to windows.GetElement in the latest version of the robot ( a similar property WaitForReady already exists on nm, that will wait for the page to stop loading before searching. )

5) This already exists on all GetElements. 
Set MinResults to 0 if you don't want an exception if nothing was found, set MinResults to 1 or higher and it will throw and error if it did not found X number of elements.

**Comment by manashk** [comment]
1,2) TimeOut already exists, and it keeps trying until the timeout occurs, so what is the point of Retry ? 
       _Agree, we can omit this, I kept it because at times due to internet connectivity or may be due to the a complecated query websites tend to slow down, so the option can be helpfull, I found it in couple of automation tool._

Visible, i could see this making sense, sometimes you can find an element that is not visible, but my definition of visible might not be what others think. for instance, if a element is visible but not on the screen ( you have to scroll for it ) is it then visible ?
I really want to make things as flexible as possible, and since different technologies treat hidden objects differently and it can have different meanings, i feel this might be a bad box of trouble to open (but I'm always open for arguments)
        _if I have to scroll to see the element, I would consider visible but might not be interactive to take click or inputs etc,_ 


This one, as far as i know, would only make sense on windows elements.
I have added and Interactive boolean to windows.GetElement in the latest version of the robot ( a similar property WaitForReady already exists on nm, that will wait for the page to stop loading before searching. ) 
       _Waitforready at times do search while the page is loading for certain websites._

This already exists on all GetElements.
Set MinResults to 0 if you don't want an exception if nothing was found, set MinResults to 1 or higher and it will throw and error if it did not found X number of elements.
         _so let me share an example, if there is a notification in the page, which doen't popup every time, this option can help, if notification is available it clicks or else moves to next activity._

**Comment by skadefro** [comment]
So we agree, all you asked for is already there ( except the Visible part, but you can just check the IsVisible / isVisibleOnScreen when looping the items and make the appropriate action.
So I'll close this ?

**Comment by manashk** [comment]
Yes you can.
I Just tried to make tool more friendly to new users. Thanks Allan.
