### ISSUE TITLE
MS Teams

### ISSUE THREAD

**Issue by arpeeay** [open-rpa/openrpa#364]
Hi Allan, I just tried to get any elements within Microsoft Teams but could get any. Do you have any idea?

Cheers, Marcus

**Comment by skadefro** [comment]
I don`t have teams, but i think it`s an elektron application, that means it does not expose the ui elements on the pages, so only image recognition will work.

**Comment by arpeeay** [comment]
Sure, but I am able to get the selectors within Uipath, so I thought this
could be an issue.

Allan Zimmermann <notifications@github.com> schrieb am Do., 30. Juli 2020,
21:57:

**Comment by skadefro** [comment]
Ok, must be something else then. I will see if i can borrow an account with teams access somewhere and investigate :-)

**Comment by skadefro** [comment]
Ok, turns out I have access to teams on my office subscription. Teams is an electron application, i have **no idea** how uipath finds the elements. 
I first tried if i could force electron to load a browser extension so i could use the NM namespace to control it, but that is not supported. Then i would have tried using chrome debugging protocol, but neither teams or slack is per default listening for debugger, so that is out of the question. Then I'm out of good ideas on how to "inject" something into electron to control it. I'm open for suggestions, but for now that means electron is still not supported.
If you or someone else finds a technology to control electron please reopen this issue or let me know on rocket chat. 🙏

**Comment by Econ808** [comment]
Hi,

Elements are available from electron applications, also Teams (see inspect.exe output below). I am not familiar with OpenRPA, I just happened to stumble upon it, however, you might want to look at something like https://github.com/pywinauto/pywinauto which "**easily**" allows for automating processes in such an app.

![image](https://user-images.githubusercontent.com/36441764/99253145-8ae84e00-2810-11eb-8951-1a519a320bc6.png)
