### ISSUE TITLE
Issue with Type Text activity when trying to type into a RDP session 

### ISSUE THREAD

**Issue by viveksjoseph** [open-rpa/openrpa#418]
**Describe the bug**
When using the Type Text Activity to write data into machine connected via RDP, the text entered is inconsistent. 

Eg: When trying to enter the string "Hello !@#", the text that actually gets entered is "hello 123"

That is: 
1) The capitalization of letters does not get send over correctly
2) The special characters does not get send over correctly. Instead the number equivalent of the same (as found on the keyboard) gets printed. 

**To Reproduce**
1. Create a windows VM
2. Connect to the VM from the PC using RDP
3. Open notepad.exe in the VM
4. In your PC, create an OpenRPA workflow that uses Type Text activity to enter the text "Hello !@#"
5. Run the workflow
6. Verify the text that was actually entered into the notepad.exe open in the VM

**Expected behavior**
The notepad.exe open in the VM should have the text "Hello !@#" instead of "hello 123"

**Desktop**
 - OS: Windows 10
 - Browser: Not Applicable
 - OpenRPA Version: 1.0.147.0

**Remote VM**
 - OS: Windows Server 2016 - Datacenter
 - Browser: Not Applicable
 - OpenRPA Version: Not Applicable

**Workflow (please complete the following information):**
[New Workflow3.zip](https://github.com/open-rpa/openrpa/files/5387474/New.Workflow3.zip)

**Additional context**
It is almost as if the shift button is not pressed when typing.

**Comment by skadefro** [comment]
Type Text has been my nemesis since day one. Maybe i choose wrong, but ....
Type Text could work in one of two ways, it could be a keyboard recording, meaning mapping the actual keys pressed, or it could be a placeholder for a string that we then send to the receiver, normally the keyboard, with whatever issues that could give when dealing with special regional settings. So i chose the first, since i want to encourage everyone to use item.text/item.value/item.sendkey etc and only use type text when you **REALLY** need to send a specific keyboard key/sequence.
So that means this is not a bug, it's an misunderstanding of what Type Text is, and when to use it.
When that is said, i just tested with a TeamViewer session and an RDP session to a Windows 2008 and Windows 2016 server and all 3 had no issues with receive lower/upper case in a pure string. But as other on rocket chat mentioned, TypeText would normally expect you to send the Shift key when you want to do Upper case
![image](https://user-images.githubusercontent.com/4155937/96294532-ce228780-0fec-11eb-84f2-0cdbbeff5edb.png)

**Comment by viveksjoseph** [comment]
Hi Allan,

I tried using the item.Sendkeys as well. But for some reason I am facing the same issue. I even updated by OpenRPA to the latest Pre-release version (1.1.3.0) without any success.

**Comment by viveksjoseph** [comment]
As we found out in our meeting, this issue occurs when using multiple displays

**Comment by skadefro** [comment]
So just to recap. We found this issue happens when robot is working with an app on another screen. I do not have access to a dual screen setup, and therefor have no way if reproducing this. Since dual screen is already on the [known issue](https://github.com/open-rpa/openrpa/wiki/Known-Issues) list i will add this to my backlog, but not work on a fix right now.
