### ISSUE TITLE
Activity moving down

### ISSUE THREAD

**Issue by manashk** [open-rpa/openrpa#427]
Hi Allan,
Every time I am executing the workflow, the activities are moving down in the view. it is strange, i encountered using v1.1.7.
![image](https://user-images.githubusercontent.com/68864590/96635209-91ef6f80-12e9-11eb-9444-fb972f825cd0.png)

**Comment by skadefro** [comment]
Is this when using invoke form, or does it happen in other cases as well?

**Comment by skadefro** [comment]
Bad robot, is not stall, i’m just bussy.

**Comment by skadefro** [comment]
I asked if you only experience this with invoke form, since that is the only place i also experience this. 
The reason it happens is, Forge.Forms requires different styles that has different sizes on some of the standard WPF elements, so when those get loaded it "pushes" some of the activities down. I cannot do anything about that, unless i 
1) use the same style everywhere, I do not want to do that, not all elements will match the styles so would not look good 
2) don't add the styles used by Forge.Forms but then the forms would be unusable since all hint's, error message and several icons depend on the styles.
So, I'll accept this is a bug, but not one I can fix, and I don't have a good work around.
But you experience this with workflow that does NOT use invoke form, I would like to know, and reopen this Issue.

**Comment by manashk** [comment]
Yes, You are correct, invoke form has been used in the workflow. 
If I face issue without invoke form in future will reopen it.
